apiVersion: v1
kind: ConfigMap
metadata:
  name: container-hash-monitor-config
  namespace: kube-system
data:
  config.yaml: |
    namespaces:
      - aether-5gc
    metrics_port: 9091
    scan_interval: 60s
    track_mode: allpods
    include_init_containers: false
