apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-hash-monitor
  namespace: kube-system
  labels:
    app: container-hash-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-hash-monitor
  template:
    metadata:
      labels:
        app: container-hash-monitor
    spec:
      serviceAccountName: container-hash-monitor
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
      - name: container-hash-monitor
        image: docker.io/sandlbn/container-hash-monitor:v1.0.1
        command:
        - "/usr/local/bin/container-hash-monitor"
        args:
        - "/etc/container-hash-monitor/config.yaml"
        ports:
        - containerPort: 9091
          name: metrics
        volumeMounts:
        - name: config
          mountPath: /etc/container-hash-monitor
        env:
        - name: RUST_LOG
          value: "info"
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
      volumes:
      - name: config
        configMap:
          name: container-hash-monitor-config
