apiVersion: v1
kind: ConfigMap
metadata:
  name: kata-monitor-config
  namespace: kube-system
data:
  config.yaml: |
    namespaces:
      - default
      - kube-system
      - production
      - staging
    metrics_port: 9090
    scan_interval: 30s
