apiVersion: v1
kind: ConfigMap
metadata:
  name: kata-monitor-config
  namespace: kube-system
data:
  config.yaml: |
    namespaces:
      - default
      - kube-system
      - production
      - staging
    metricsPort: 9090
    scanInterval: 30s
    kubeconfigPath: /etc/kubeconfig/admin.conf
