resources:
  - ./configmap.yaml
  - ./serviceaccount-rbac.yaml
  - ./daemonset.yaml
  - ./service.yaml
  - ./servicemonitor.yaml

configMapGenerator:
  - name: grafana-ops-dashboards
    namespace: cattle-dashboards
    files:
      - ./coco-dashboard.json
generatorOptions:
  labels:
    grafana_dashboard: "1"
