apiVersion: v1
kind: ConfigMap
metadata:
  name: container-hash-monitor-config
  namespace: kube-system
data:
  config.yaml: |
    namespaces:
      - default
      - kube-system
      - production
      - staging
    metrics_port: 9091
    scan_interval: 60s
    kubeconfig_path: ""
    track_mode: services
    include_init_containers: false
