apiVersion: v1
kind: Service
metadata:
  name: container-hash-monitor
  namespace: kube-system
  labels:
    app: container-hash-monitor
spec:
  selector:
    app: container-hash-monitor
  ports:
  - name: metrics
    port: 9091
    targetPort: 9091
